### ISSUE TITLE
Weird parsing with substractions

### ISSUE THREAD

**Issue by simoheinonen** [NeonXP/MathExecutor#19]
```php
<?php
require_once 'vendor/autoload.php';
echo (new \NXP\MathExecutor())->execute('1-1') . PHP_EOL;
```

```
PHP Fatal error:  Uncaught exception 'NXP\Exception\IncorrectExpressionException' in /home/xx/yy/vendor/nxp/math-executor/src/NXP/Classes/Calculator.php:57
Stack trace:
#0 /home/xx/yy/vendor/nxp/math-executor/src/NXP/MathExecutor.php(191): NXP\Classes\Calculator->calculate(Array, Array)
#1 /home/xx/yy/jee.php(3): NXP\MathExecutor->execute('1-1')
#2 {main}
  thrown in /home/xx/yy/vendor/nxp/math-executor/src/NXP/Classes/Calculator.php on line 57
```

**Comment by phpfui** [comment]
This should work now.
